<a href="https://colab.research.google.com/github/Prakash-076/Python-Machine-Learning/blob/main/Skill_Test_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler

# Feature data
X = np.array([
    [1, 50, 1, 2],
    [1.5, 60, 0.5, 3],
    [0.8, 55, 1.2, 1.6],
    [2, 40, 1, 4],
    [1.2, 65, 0.8, 2.4],
    [1.7, 45, 1.5, 3.4],
    [0.9, 70, 1, 1.8],
    [2.1, 35, 1.3, 4.2],
    [1.1, 60, 0.9, 2.2],
    [1.8, 48, 1, 3.6],
    [0.95, 62, 1.1, 1.9],
    [2.2, 42, 0.7, 4.4],
    [1, 58, 1, 2],
    [1.9, 46, 1.2, 3.8],
    [1.3, 66, 0.6, 2.6]
])

# Labels (Sine=0, Square=1)
y = np.array([0,1,0,1,0,1,0,1,0,1,0,1,0,1,0])

# Feature scaling (important for KNN)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Create KNN model
k = 3
model = KNeighborsClassifier(n_neighbors=k)

# Train model
model.fit(X_scaled, y)

# Example prediction
new_signal = np.array([[1.4, 55, 1, 2.8]])
new_signal_scaled = scaler.transform(new_signal)

prediction = model.predict(new_signal_scaled)

print("Predicted Class:", "Sine" if prediction[0] == 0 else "Square")

Predicted Class: Sine


In [4]:
import numpy as np
from sklearn.neighbors import KNeighborsClassifier

# Feature dataset: [Voltage, Current]
X = np.array([
    [5, 0.5],
    [5.5, 0.4],
    [4.8, 0.6],
    [6, 0.3],
    [6.5, 0.2],
    [6.2, 0.25],
    [4.9, 0.55],
    [5.8, 0.35],
    [5.2, 0.5],
    [6.3, 0.22]
])

# Labels: Working = 0, Defective = 1
y = np.array([
    0, 0, 0, 1, 1,
    1, 0, 1, 0, 1
])

# Create KNN model
model = KNeighborsClassifier(n_neighbors=3)

# Train the model
model.fit(X, y)

# Predict on same dataset (since no test data given)
predictions = model.predict(X)

# Print results
print("Predicted Labels:")
print(predictions)

print("Actual Labels:")
print(y)

Predicted Labels:
[0 0 0 1 1 1 0 1 0 1]
Actual Labels:
[0 0 0 1 1 1 0 1 0 1]


In [5]:
import numpy as np
from sklearn.linear_model import LinearRegression

# Given dataset
# Study Hours (X)
X = np.array([3, 4, 5, 6, 7, 8, 9, 10, 11, 12]).reshape(-1, 1)

# Final Exam Scores (y)
y = np.array([50, 55, 60, 65, 68, 70, 78, 75, 82, 85])

# Create Linear Regression model
model = LinearRegression()

# Train the model
model.fit(X, y)

# Predict scores for the same inputs (since no new data is given)
predictions = model.predict(X)

# Print predictions
print("Predicted Scores:")
print(predictions)

# Print actual scores
print("Actual Scores:")
print(y)

# Example: Predict score for a new student who studies 7.5 hours
new_hours = np.array([[7.5]])
predicted_score = model.predict(new_hours)

print("Predicted score for 7.5 study hours:", predicted_score[0])

Predicted Scores:
[51.89090909 55.64848485 59.40606061 63.16363636 66.92121212 70.67878788
 74.43636364 78.19393939 81.95151515 85.70909091]
Actual Scores:
[50 55 60 65 68 70 78 75 82 85]
Predicted score for 7.5 study hours: 68.8


In [6]:
import numpy as np
from sklearn.linear_model import LinearRegression

# Given dataset
# Year (independent variable)
X = np.array([2010, 2011, 2012, 2013, 2014,
              2015, 2016, 2017, 2018, 2019]).reshape(-1, 1)

# Price in Lakhs (dependent variable)
y = np.array([25, 28, 30, 34, 37, 40, 43, 45, 47, 50])

# Create Linear Regression model
model = LinearRegression()

# Train the model
model.fit(X, y)

# Predict prices for given years
predictions = model.predict(X)

# Print predicted prices
print("Predicted Prices:")
print(predictions)

# Print actual prices
print("Actual Prices:")
print(y)

# Example: Predict price for year 2020
future_year = np.array([[2020]])
predicted_price = model.predict(future_year)

print("Predicted price for 2020 (in Lakhs):", predicted_price[0])

Predicted Prices:
[25.27272727 28.07878788 30.88484848 33.69090909 36.4969697  39.3030303
 42.10909091 44.91515152 47.72121212 50.52727273]
Actual Prices:
[25 28 30 34 37 40 43 45 47 50]
Predicted price for 2020 (in Lakhs): 53.33333333333303


In [7]:
import numpy as np
from sklearn.tree import DecisionTreeClassifier

# Encode Transmitter: T1=1, T2=2, T3=3
# Features: [Transmitter, Signal Strength, Frequency]
X = np.array([
    [1, 75, 2000],
    [2, 50, 1500],
    [1, 90, 2200],
    [3, 40, 1300],
    [2, 85, 2100],
    [1, 70, 1800],
    [3, 30, 1200],
    [2, 60, 1600],
    [1, 80, 1900],
    [3, 20, 1100]
])

# Labels: Good=1, Bad=0
y = np.array([1, 0, 1, 0, 1, 1, 0, 0, 1, 0])

# Create Decision Tree model
model = DecisionTreeClassifier()

# Train the model
model.fit(X, y)

# Predict on same dataset
predictions = model.predict(X)

# Print results
print("Predicted Signal Quality:")
print(predictions)

print("Actual Signal Quality:")
print(y)

# Example: Predict new signal
# Example input: T2, Strength=65, Frequency=1700
new_signal = np.array([[2, 65, 1700]])
prediction = model.predict(new_signal)

print("Prediction for new signal:",
      "Good" if prediction[0] == 1 else "Bad")

Predicted Signal Quality:
[1 0 1 0 1 1 0 0 1 0]
Actual Signal Quality:
[1 0 1 0 1 1 0 0 1 0]
Prediction for new signal: Bad


In [8]:
import numpy as np
from sklearn.cluster import KMeans

# Given dataset: [Voltage, Current]
X = np.array([
    [4.819941, 0.87293],
    [5.249786, 0.918358],
    [4.771151, 0.958775],
    [4.602712, 1.087788],
    [4.814919, 0.877739],
    [12.38281, 2.257141],
    [12.36406, 2.383657],
    [11.22958, 1.89107],
    [12.17975, 1.82507],
    [12.0638, 2.29575]
])

# Apply KMeans with 2 clusters
kmeans = KMeans(n_clusters=2, random_state=0)

# Fit the model
kmeans.fit(X)

# Get cluster labels
labels = kmeans.labels_

# Get cluster centers
centers = kmeans.cluster_centers_

# Print results
print("Cluster Labels:")
print(labels)

print("\nCluster Centers:")
print(centers)

Cluster Labels:
[1 1 1 1 1 0 0 0 0 0]

Cluster Centers:
[[12.044      2.1305376]
 [ 4.8517018  0.943118 ]]
